### ISSUE TITLE
EPIC: Дизайн

### ISSUE THREAD

**Issue by Slermo** [ru-skord/design_ruskord#5]
Сделать дизайн для
- [ ] [#1](https://github.com/ru-skord/design_ruskord/issues/1)
- [ ] [#2](https://github.com/ru-skord/design_ruskord/issues/2)
- [ ] [#3](https://github.com/ru-skord/design_ruskord/issues/3)
- [ ] [#4](https://github.com/ru-skord/design_ruskord/issues/4)
